name: Check PR

on:
  pull_request:
    branches: [$default-branch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
