name: Deploy Staging

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Archive Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          path: |
            cypress/screenshots
            cypress/videos

  build:
    needs: [lint, run-unit-tests, run-e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Build production artifacts
        run: npm run build:production

      - name: Archive production artifiacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Install npm dependencies
        run: npm ci

      - name: Deploy
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_SYNC_BUCKET: staging.play.generative.fm
          S3_SYNC_DISTRIBUTION_ID: E3SA4H8H9ICHU9
